import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const ADDITIONAL_QUESTIONS = [
  // friends (50)
  { question: '[שם], מה הדבר הכי דבילי שעשית כדי להרשים מישהו/י?', category: 'friends' },
  { question: '[שם], אם היית חייב/ת למחוק איש קשר אחד מהשולחן – מי זה היה?', category: 'friends' },
  { question: '[שם], מה הסטורי הכי מביך שהעלית ומחקת אחרי דקה?', category: 'friends' },
  { question: '[שם], מי כאן הכי "קמצן" כשמגיע החשבון?', category: 'friends' },
  { question: '[שם], מה הדבר הכי לא חוקי שעשית ואף אחד לא יודע?', category: 'friends' },
  { question: '[שם], אם היית דמות ב"קופה ראשית", מי היית?', category: 'friends' },
  { question: '[שם], מה השקר הכי גדול שסיפרת ב"דייט ראשון"?', category: 'friends' },
  { question: '[שם], מי כאן הכי סביר שיעבור לגור בתאילנד ויפתח דוכן שייקים?', category: 'friends' },
  { question: '[שם], מה המנה הכי מגעילה שאכלת רק כי זה היה יקר?', category: 'friends' },
  { question: '[שם], מי כאן "חופר" בוואטסאפ יותר מדי?', category: 'friends' },
  { question: '[שם], מה הכינוי הכי דפוק שנתנו לך בבית ספר?', category: 'friends' },
  { question: '[שם], אם היית חייב/ת להתחתן עם מישהו מהשולחן – במי היית בוחר/ת?', category: 'friends' },
  { question: '[שם], מה הדבר הכי מגעיל שעשית בבית של חבר?', category: 'friends' },
  { question: '[שם], מה הדבר הראשון שהיית קונה אם היית זוכה בלוטו?', category: 'friends' },
  { question: '[שם], מי כאן הכי סביר שייעצר על ידי המשטרה?', category: 'friends' },
  { question: '[שם], מה השיר שאת/ה שר/ה בסתר במקלחת?', category: 'friends' },
  { question: '[שם], מי כאן יסיים את הלילה עם הכי הרבה צ\'ייסרים?', category: 'friends' },
  { question: '[שם], מה התירוץ הכי גרוע שהמצאת כדי להבריז למפגש חברים?', category: 'friends' },
  { question: '[שם], איזה שחקן/ית היו משחקים אותך בסרט על חייך?', category: 'friends' },
  { question: '[שם], מה הפחד הכי מטופש שלך?', category: 'friends' },
  { question: '[שם], מי מהנוכחים הכי סביר שיהיה ראש הממשלה?', category: 'friends' },
  { question: '[שם], מה המנה שהיית בוחר/ת לארוחה האחרונה שלך?', category: 'friends' },
  { question: '[שם], מה הדבר הכי מוזר שיש לך בתיק/בכיס כרגע?', category: 'friends' },
  { question: '[שם], מי כאן הכי "דרמה קווין"?', category: 'friends' },
  { question: '[שם], מה העבודה הכי גרועה שעבדת בה?', category: 'friends' },
  { question: '[שם], מה הדבר הכי נועז שאי פעם אכלת?', category: 'friends' },
  { question: '[שם], מי כאן הכי סביר שישכח את יום ההולדת שלך?', category: 'friends' },
  { question: '[שם], מה הפעם האחרונה שבכית מצחוק?', category: 'friends' },
  { question: '[שם], מה היה הניק הראשון שלך באיסיקיו/מסנג\'ר?', category: 'friends' },
  { question: '[שם], אם היית סופר-גיבור, מה היה הכוח שלך?', category: 'friends' },
  { question: '[שם], מי כאן הכי סביר שיגיע לאירוע עם נעלי בית?', category: 'friends' },
  { question: '[שם], מה הדבר שהכי מעצבן אותך באנשים?', category: 'friends' },
  { question: '[שם], מה הפדיחה הכי גדולה שקרתה לך בטיול בחו"ל?', category: 'friends' },
  { question: '[שם], מה הריב הכי מטופש שהיה לך עם מישהו מהשולחן?', category: 'friends' },
  { question: '[שם], מה ההרגל הכי מוזר שיש לך כשאת/ה לבד בבית?', category: 'friends' },
  { question: '[שם], מי כאן הכי סביר שיירדם באמצע מסיבה?', category: 'friends' },
  { question: '[שם], מה הדבר הכי יקר שקנית והתחרטת עליו?', category: 'friends' },
  { question: '[שם], מה היה החלום שלך כשהיית קטן/ה?', category: 'friends' },
  { question: '[שם], מי כאן הכי "מכור" לאינסטגרם?', category: 'friends' },
  { question: '[שם], מה הריח האהוב עליך?', category: 'friends' },
  { question: '[שם], מה הזיכרון הכי חזק שיש לך מהתיכון?', category: 'friends' },
  { question: '[שם], מי מהשולחן היה שורד הכי הרבה זמן ב"הישרדות"?', category: 'friends' },
  { question: '[שם], מה הטעות הכי גדולה שעשית בשיקול דעת?', category: 'friends' },
  { question: '[שם], מה הדבר הכי רומנטי שעשית אי פעם?', category: 'friends' },
  { question: '[שם], מי כאן הכי סביר שיעשה קעקוע של הלוגו של עלינא?', category: 'friends' },
  { question: '[שם], מה הדבר הראשון שאת/ה עושה כשאת/ה קם/ה בבוקר?', category: 'friends' },
  { question: '[שם], מה המקום הכי יפה שהיית בו בעולם?', category: 'friends' },
  { question: '[שם], מה היית משנה בעצמך אם היית יכול/ה?', category: 'friends' },
  { question: '[שם], מה הכי מרגיע אותך?', category: 'friends' },
  { question: '[שם], מי מהשולחן הכי סביר שישלם על כולם היום?', category: 'friends' },

  // date (50)
  { question: '[שם], מה היה הרושם הראשוני שלך על הפרטנר/ית?', category: 'date' },
  { question: '[שם], מה המנה שהפרטנר/ית הכי אוהבת?', category: 'date' },
  { question: '[שם], מה הרגע שבו הבנת שאת/ה מאוהב/ת?', category: 'date' },
  { question: '[שם], איפה את/ה רואה אותנו בעוד 5 שנים?', category: 'date' },
  { question: '[שם], מה הדבר הכי מוזר שהפרטנר/ית עושה כשהוא/היא ישן/ה?', category: 'date' },
  { question: '[שם], מה היה הדייט הכי גרוע שהיית בו (לפנינו)?', category: 'date' },
  { question: '[שם], מה התכונה שאת/ה הכי מעריך/ה בפרטנר/ית?', category: 'date' },
  { question: '[שם], איזה שיר תמיד מזכיר לך אותנו?', category: 'date' },
  { question: '[שם], אם היינו עוברים למדינה אחרת, לאן זה היה?', category: 'date' },
  { question: '[שם], מה הקנייה הכי מטופשת שעשינו יחד?', category: 'date' },
  { question: '[שם], מי אמר "אני אוהב/ת אותך" קודם?', category: 'date' },
  { question: '[שם], מה הסרט שהכי מזכיר לך את הקשר שלנו?', category: 'date' },
  { question: '[שם], מה הטיול הכי יפה שעשינו יחד?', category: 'date' },
  { question: '[שם], מה הדבר הראשון שחשבת עליי כשראית אותי באפליקציה/בבר?', category: 'date' },
  { question: '[שם], מה הדבר שהכי מצחיק אותך בפרטנר/ית?', category: 'date' },
  { question: '[שם], מה המתנה הכי יפה שקיבלת ממני?', category: 'date' },
  { question: '[שם], מה הריח שלי שאת/ה הכי אוהב/ת?', category: 'date' },
  { question: '[שם], מה הפדיחה הכי גדולה שקרתה לנו יחד בציבור?', category: 'date' },
  { question: '[שם], מי לדעתך שולט בשלט של הטלוויזיה בבית?', category: 'date' },
  { question: '[שם], מה הדבר הכי רומנטי שעשיתי עבורך?', category: 'date' },
  { question: '[שם], מה המקום המועדף עליך לנשיקה?', category: 'date' },
  { question: '[שם], מה את/ה הכי אוהב/ת לאכול כשאני מבשל/ת?', category: 'date' },
  { question: '[שם], איזה בגד שלי את/ה הכי פחות אוהב/ת?', category: 'date' },
  { question: '[שם], מה היה הרגע הכי מרגש בחתונה/ביום שהכרנו?', category: 'date' },
  { question: '[שם], מה החלום הכי גדול שאת/ה רוצה להגשים איתי?', category: 'date' },
  { question: '[שם], מה התכונה שהכי דומה בינינו?', category: 'date' },
  { question: '[שם], מה הדבר הכי "קיטשי" שאת/ה אוהב/ת לעשות איתי?', category: 'date' },
  { question: '[שם], מה את/ה הכי מעריץ/ה בדרך שבה אני מתמודד/ת עם קשיים?', category: 'date' },
  { question: '[שם], מה הדבר הכי מוזר שאמרתי לך אי פעם?', category: 'date' },
  { question: '[שם], מי מאיתנו יותר עקשן?', category: 'date' },
  { question: '[שם], מה הדבר הכי סקסי בעיניך אצלי?', category: 'date' },
  { question: '[שם], מה המקום הראשון שבו טיילנו יחד?', category: 'date' },
  { question: '[שם], מה הדבר הכי חשוב שלמדת מהקשר הזה?', category: 'date' },
  { question: '[שם], מה המסורת הכי חמודה שיש לנו?', category: 'date' },
  { question: '[שם], מה הדבר הכי יפה שאמרתי לך אי פעם?', category: 'date' },
  { question: '[שם], מי מאיתנו יותר "בלאגניסט" בבית?', category: 'date' },
  { question: '[שם], מה המאכל שאת/ה תמיד גונב/ת לי מהצלחת?', category: 'date' },
  { question: '[שם], מה את/ה הכי אוהב/ת לעשות איתי ביום חופש?', category: 'date' },
  { question: '[שם], מה הדבר הכי מפתיע שגילית עליי?', category: 'date' },
  { question: '[שם], מה התכונה שהכי משלימה אותנו?', category: 'date' },
  { question: '[שם], מה הדבר הכי נועז שעשינו יחד?', category: 'date' },
  { question: '[שם], איזה סוג הורים נהיה לדעתך?', category: 'date' },
  { question: '[שם], מה הדבר הראשון שתעשה/י כשתחזור/י הביתה הלילה?', category: 'date' },
  { question: '[שם], מה הזיכרון הכי חזק שלך מהדייט הראשון?', category: 'date' },
  { question: '[שם], מה את/ה הכי אוהב/ת בחיבוק שלי?', category: 'date' },
  { question: '[שם], מה היית משנה בדייט הראשון שלנו אם היית יכול/ה?', category: 'date' },
  { question: '[שם], מה השיר שלנו?', category: 'date' },
  { question: '[שם], מה את/ה הכי מחכה לו בערב הזה?', category: 'date' },
  { question: '[שם], מה הדבר הכי מיוחד ששמרת ממני?', category: 'date' },
  { question: '[שם], כמה ילדים את/ה רוצה שיהיו לנו (בלי לחץ)?', category: 'date' },

  // family (50)
  { question: '[שם], מי כאן היה הילד הכי בעייתי בבית?', category: 'family' },
  { question: '[שם], מה המנה שאמא/אבא מכינים שאף פעם לא נמאס לך ממנה?', category: 'family' },
  { question: '[שם], מה השקר הכי גדול שסיפרת להורים כשהיית נער/ה?', category: 'family' },
  { question: '[שם], מי כאן הכי דומה לסבא או לסבתא?', category: 'family' },
  { question: '[שם], מה הזיכרון המשפחתי הכי מצחיק שלך?', category: 'family' },
  { question: '[שם], מי כאן הולך להיות "הדוד המביך" בעתיד?', category: 'family' },
  { question: '[שם], מה המנה שסימלה את הילדות שלך?', category: 'family' },
  { question: '[שם], מי מבני המשפחה הכי "חפרן" בארוחות שבת?', category: 'family' },
  { question: '[שם], מה הטיול המשפחתי הכי בלתי נשכח שהיה לנו?', category: 'family' },
  { question: '[שם], מה הדבר הכי חשוב שלמדת מאמא/אבא?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שיישאר לגור אצל ההורים עד גיל 40?', category: 'family' },
  { question: '[שם], מה המסורת המשפחתית שאת/ה הכי אוהב/ת?', category: 'family' },
  { question: '[שם], מי כאן "המוח" של המשפחה?', category: 'family' },
  { question: '[שם], מה הפעם האחרונה שבאמת התגאית במישהו מהמשפחה?', category: 'family' },
  { question: '[שם], מי מבני המשפחה כאן הכי רגשן?', category: 'family' },
  { question: '[שם], מה השם שרצית שיהיה לך כשהיית קטן/ה?', category: 'family' },
  { question: '[שם], מה הדבר הכי מעצבן ש[שם אחר] עושה בארוחות?', category: 'family' },
  { question: '[שם], מה התכונה הכי בולטת שקיבלת מההורים?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שיהפוך למיליונר?', category: 'family' },
  { question: '[שם], מה היה החפץ הכי אהוב עליך בילדות?', category: 'family' },
  { question: '[שם], מה המשפט שמישהו מההורים תמיד אומר וזה משגע את כולם?', category: 'family' },
  { question: '[שם], מי מהמשפחה כאן מבשל הכי גרוע?', category: 'family' },
  { question: '[שם], מה הזיכרון הכי מוקדם שיש לך מהבית?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שיעשה פדיחה בחתונה משפחתית?', category: 'family' },
  { question: '[שם], מה הדבר שהכי השתנה במשפחה שלנו בעשור האחרון?', category: 'family' },
  { question: '[שם], מה המקום המועדף עליך לטיול משפחתי?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שיהיה הורה קשוח?', category: 'family' },
  { question: '[שם], מה הפעם האחרונה שצחקנו יחד עד דמעות?', category: 'family' },
  { question: '[שם], מה הדבר הכי נועז שמישהו מהמשפחה עשה?', category: 'family' },
  { question: '[שם], מה הערך הכי חשוב שיש למשפחה שלנו?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שישכח להביא מתנה לחג?', category: 'family' },
  { question: '[שם], מה התחביב הכי מוזר של מישהו מהמשפחה?', category: 'family' },
  { question: '[שם], מה הדבר הראשון שהיית עושה אם היית זוכה בלוטו (עבור המשפחה)?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שיישאר לישון על הספה בסלון?', category: 'family' },
  { question: '[שם], מה המנה שחייבת להיות בכל שולחן חג אצלנו?', category: 'family' },
  { question: '[שם], מה הדבר הכי מצחיק שאחד הילדים במשפחה אמר לאחרונה?', category: 'family' },
  { question: '[שם], מי כאן הכי "מכור" לטלפון בארוחות?', category: 'family' },
  { question: '[שם], מה הזיכרון הכי חזק שלך מחופשה משפחתית בקיץ?', category: 'family' },
  { question: '[שם], מה הדבר הכי יפה שמישהו מהמשפחה עשה עבורך?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שיתחיל לשיר באמצע הרחוב?', category: 'family' },
  { question: '[שם], מה הכינוי המביך שלך בתוך המשפחה?', category: 'family' },
  { question: '[שם], מה המנה ש[שם אחר] מכין/ה ואף אחד לא מעז להגיד שהיא לא טעימה?', category: 'family' },
  { question: '[שם], מי כאן הכי "דרמטי" כשמישהו חולה?', category: 'family' },
  { question: '[שם], מה הדבר הכי טוב שקרה למשפחה השנה?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שיהפוך למפורסם?', category: 'family' },
  { question: '[שם], מה המשחק המשפחתי שהכי אהבת כשהיית קטן/ה?', category: 'family' },
  { question: '[שם], מה הדבר שהכי מחבר בינינו כמשפחה?', category: 'family' },
  { question: '[שם], מה היית משנה בבית שגדלת בו?', category: 'family' },
  { question: '[שם], מי כאן הכי סביר שיאמץ 10 חתולים?', category: 'family' },
  { question: '[שם], מה הדבר הראשון שנעשה יחד אחרי הארוחה?', category: 'family' },

  // bday (50)
  { question: '[שם], מה המתנה הכי גרועה שקיבלת אי פעם?', category: 'bday' },
  { question: '[שם], מה היית מאחל/ת לבעל/ת השמחה לשנה הקרובה?', category: 'bday' },
  { question: '[שם], מה יום ההולדת הכי בלתי נשכח שהיה לך?', category: 'bday' },
  { question: '[שם], אם היית יכול/ה להזמין כל סלב למסיבה שלך – מי זה היה?', category: 'bday' },
  { question: '[שם], מה היעד שבו היית רוצה לחגוג את יום ההולדת הבא?', category: 'bday' },
  { question: '[שם], מה הדבר הכי "משוגע" שעשית ביום הולדת?', category: 'bday' },
  { question: '[שם], מה הזיכרון הכי יפה שלך מיום הולדת בילדות?', category: 'bday' },
  { question: '[שם], מה הגיל שהכי נהנית בו עד עכשיו?', category: 'bday' },
  { question: '[שם], מי מהנוכחים כאן יביא את המתנה הכי מקורית?', category: 'bday' },
  { question: '[שם], מה הדבר הכי חשוב שלמדת בשנה האחרונה?', category: 'bday' },
  { question: '[שם], אם היית צריך/ה לבחור עוגה אחת לכל החיים – איזו זו הייתה?', category: 'bday' },
  { question: '[שם], מה התחביב החדש שהיית רוצה להתחיל השנה?', category: 'bday' },
  { question: '[שם], מה הדבר הראשון שתעשה/י מחר בבוקר?', category: 'bday' },
  { question: '[שם], מי כאן הכי סביר שיארגן מסיבת הפתעה?', category: 'bday' },
  { question: '[שם], מה המתנה הכי מרגשת שקיבלת אי פעם?', category: 'bday' },
  { question: '[שם], מה השיר שחייב להיות בכל מסיבת יום הולדת?', category: 'bday' },
  { question: '[שם], מה הדבר שהכי השתנה בך מאז יום ההולדת הקודם?', category: 'bday' },
  { question: '[שם], מה את/ה הכי אוהב/ת בבעל/ת השמחה?', category: 'bday' },
  { question: '[שם], מה הזיכרון הכי מצחיק שיש לך עם בעל/ת השמחה?', category: 'bday' },
  { question: '[שם], מה הדבר הכי נועז שבעל/ת השמחה עשה/תה השנה?', category: 'bday' },
  { question: '[שם], מי כאן הכי סביר שישיר הכי חזק "היום יום הולדת"?', category: 'bday' },
  { question: '[שם], מה המקום הכי מוזר שבו חגגת יום הולדת?', category: 'bday' },
  { question: '[שם], מה הדבר שהכי משמח אותך בימי הולדת?', category: 'bday' },
  { question: '[שם], מה היית רוצה לשנות בשנה הבאה?', category: 'bday' },
  { question: '[שם], מה הדבר הראשון שחשבת כשקמת הבוקר?', category: 'bday' },
  { question: '[שם], מי כאן הכי סביר שיישאר אחרון במסיבה?', category: 'bday' },
  { question: '[שם], מה המתנה הכי יקרה שקנית למישהו?', category: 'bday' },
  { question: '[שם], מה הדבר הכי יפה שמישהו אמר לך ביום הולדת?', category: 'bday' },
  { question: '[שם], מה היית מאחל/ת לעצמך לעשור הקרוב?', category: 'bday' },
  { question: '[שם], מה הדבר הכי מצחיק שקרה ביום הולדת של מישהו אחר כאן?', category: 'bday' },
  { question: '[שם], מה המנה שחייבת להיות בכל שולחן יומולדת?', category: 'bday' },
  { question: '[שם], מה היית עושה אם היית זוכה במיליון דולר ביום ההולדת שלך?', category: 'bday' },
  { question: '[שם], מי כאן הכי סביר שיאבד את הטלפון במסיבה?', category: 'bday' },
  { question: '[שם], מה הדבר הכי מפתיע שקרה לך ביום הולדת?', category: 'bday' },
  { question: '[שם], מה את/ה הכי אוהב/ת לקבל כמתנה?', category: 'bday' },
  { question: '[שם], מה היית משנה במסיבה הזו אם היית יכול/ה?', category: 'bday' },
  { question: '[שם], מי כאן הכי סביר שיבכה מהתרגשות מהברכות?', category: 'bday' },
  { question: '[שם], מה הדבר הכי חשוב שקרה לך השנה?', category: 'bday' },
  { question: '[שם], מה הטיפ הכי טוב שאת/ה יכול/ה לתת לבעל/ת השמחה?', category: 'bday' },
  { question: '[שם], מה הדבר הראשון שבעל/ת השמחה צריך/כה לעשות מחר?', category: 'bday' },
  { question: '[שם], מי כאן הכי סביר שיביא עוגה קנויה ויגיד שהוא הכין?', category: 'bday' },
  { question: '[שם], מה הדבר שהכי מחבר בין כל האנשים כאן בשולחן?', category: 'bday' },
  { question: '[שם], מה הזיכרון הכי חזק שלך מגיל 18?', category: 'bday' },
  { question: '[שם], מה היית רוצה לעשות ביום ההולדת הבא שלך?', category: 'bday' },
  { question: '[שם], מה המילה אחת שמתארת הכי טוב את בעל/ת השמחה?', category: 'bday' },
  { question: '[שם], מי כאן הכי סביר שיזמין את הצ\'ייסר הבא לשולחן?', category: 'bday' },
  { question: '[שם], מה הדבר הכי יפה שראית השנה?', category: 'bday' },
  { question: '[שם], מה היית עושה אם היית יכול/ה לעצור את הזמן היום?', category: 'bday' },
  { question: '[שם], מה הברכה הכי מקורית שקיבלת היום?', category: 'bday' },
  { question: '[שם], מה הדבר הראשון שתגיד/י לבעל/ת השמחה בסוף הערב?', category: 'bday' },

  // girls (50)
  { question: '[שם], מה הדבר הראשון שאת מסתכלת עליו בגבר?', category: 'girls' },
  { question: '[שם], מה המקום הכי מוזר שעשית בו סקס?', category: 'girls' },
  { question: '[שם], מה ה-Turn-off הכי גדול שלך במיטה?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתחזור הביתה עם מישהו שהיא הכירה הלילה?', category: 'girls' },
  { question: '[שם], מה הפנטזיה הכי פרועה שלך שעדיין לא הגשמת?', category: 'girls' },
  { question: '[שם], איזה אביזר "מעניין" יש לך במגירה בבית?', category: 'girls' },
  { question: '[שם], מה היה הסטוץ הכי גרוע שהיה לך?', category: 'girls' },
  { question: '[שם], אם היית חייבת להתנשק עם אחת הבנות כאן – מי זו הייתה?', category: 'girls' },
  { question: '[שם], מה הדבר הכי נועז ששלחת ב-DM?', category: 'girls' },
  { question: '[שם], מי כאן הכי "שובבה" במיטה?', category: 'girls' },
  { question: '[שם], מה היית עושה אם היית הופכת לגבר ליום אחד?', category: 'girls' },
  { question: '[שם], מה הדבר הכי מביך שקרה לך בזמן סקס?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתתחיל עם הברמן?', category: 'girls' },
  { question: '[שם], מה הדייט הכי הזוי שהיית בו דרך אפליקציה?', category: 'girls' },
  { question: '[שם], מה החלק בגוף שאת הכי אוהבת אצלך?', category: 'girls' },
  { question: '[שם], מה ה-Move הכי חזק שלך כשאת רוצה להשיג מישהו?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתשלח הודעה לאקס הלילה?', category: 'girls' },
  { question: '[שם], מה השקר הכי גדול שסיפרת במיטה?', category: 'girls' },
  { question: '[שם], מה הדבר הכי מוזר שמישהו ביקש ממך במיטה?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתעשה סטוץ בחופשה בחו"ל?', category: 'girls' },
  { question: '[שם], מה המקום הכי נועז שחשבת עליו לסקס?', category: 'girls' },
  { question: '[שם], מה הדבר הכי "רעיל" שעשית במערכת יחסים?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתתחתן ראשונה (או שוב)?', category: 'girls' },
  { question: '[שם], מה ה-Red Flag הכי גדול שלך?', category: 'girls' },
  { question: '[שם], מה הפעם האחרונה שזייפת אורגזמה?', category: 'girls' },
  { question: '[שם], מה הדבר הכי יקר שקנית כדי להרגיש סקסית?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתצא עם מישהו צעיר ממנה ב-10 שנים?', category: 'girls' },
  { question: '[שם], מה הטיפ הכי טוב שקיבלת על סקס?', category: 'girls' },
  { question: '[שם], מה הדבר הכי רומנטי (או מיני) שמישהו עשה עבורך?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתהיה בתוכנית ריאליטי?', category: 'girls' },
  { question: '[שם], מה המילה שאת הכי שונאת שגברים אומרים?', category: 'girls' },
  { question: '[שם], מה הפעם האחרונה שהרגשת ממש נחשקת?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתעשה קעקוע משותף עם חברה?', category: 'girls' },
  { question: '[שם], מה הדבר הכי נועז שלבשת אי פעם?', category: 'girls' },
  { question: '[שם], מה הדרינק שמוציא ממך את הצד השובב?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתתחיל עם מישהו במכון כושר?', category: 'girls' },
  { question: '[שם], מה הדבר הכי מוזר שמשך אותך במישהו?', category: 'girls' },
  { question: '[שם], מה הסוד הכי גדול שסיפרת רק לאחת הבנות כאן?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתהפוך למשפיענית אינסטגרם?', category: 'girls' },
  { question: '[שם], מה היית עושה אם היית מגלה שהחבר/בעל שלך בוגד?', category: 'girls' },
  { question: '[שם], מה הדבר הכי יפה שמישהי כאן אמרה לך אי פעם?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתזמין את הפינוק הבא לשולחן?', category: 'girls' },
  { question: '[שם], מה הפעם האחרונה שהתחלת עם מישהו בעצמך?', category: 'girls' },
  { question: '[שם], מה הדבר הכי "מלוכלך" שאמרת בטלפון?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתעזוב הכל ותעבור לחיות בחו"ל?', category: 'girls' },
  { question: '[שם], מה הדבר שהכי מרגיע אותך אחרי יום קשה?', category: 'girls' },
  { question: '[שם], מה הפנטזיה הכי גדולה שלך לגבי העתיד?', category: 'girls' },
  { question: '[שם], מי כאן הכי סביר שתהיה הבוסית של כולנו?', category: 'girls' },
  { question: '[שם], מה המילה אחת שמתארת הכי טוב את הערב הזה?', category: 'girls' },
  { question: '[שם], מה הדבר הראשון שתעשי כשתתעוררי מחר בבוקר?', category: 'girls' },

  // business (50)
  { question: '[שם], מה הייתה העבודה הראשונה שלך אי פעם?', category: 'business' },
  { question: '[שם], מה הטעות הכי גדולה שעשית בקריירה ומה למדת ממנה?', category: 'business' },
  { question: '[שם], מה היעד המקצועי הבא שאת/ה רוצה לכבוש?', category: 'business' },
  { question: '[שם], אם לא היית במקצוע הנוכחי – מה היית עושה?', category: 'business' },
  { question: '[שם], מה התכונה הכי חשובה לדעתך אצל שותף עסקי?', category: 'business' },
  { question: '[שם], מה הספר/פודקאסט ששינה לך את הדרך שבה את/ה עובד/ת?', category: 'business' },
  { question: '[שם], איך את/ה משחרר/ת לחץ אחרי יום עבודה מטורף?', category: 'business' },
  { question: '[שם], מה העצה הכי טובה שקיבלת מהבוס הראשון שלך?', category: 'business' },
  { question: '[שם], אם היית יכול/ה להשקיע מיליון דולר במיזם אחד – מה זה היה?', category: 'business' },
  { question: '[שם], מה המשקה שבלעדיו אי אפשר להתחיל את יום העבודה?', category: 'business' },
  { question: '[שם], מה הפרויקט שאת/ה הכי גאה בו עד היום?', category: 'business' },
  { question: '[שם], מי כאן הכי סביר שיהיה המנכ"ל הבא של חברה גדולה?', category: 'business' },
  { question: '[שם], מה הטיפ הכי טוב שאת/ה יכול/ה לתת ליזם מתחיל?', category: 'business' },
  { question: '[שם], מה הדבר שהכי מעצבן אותך בפגישות עבודה?', category: 'business' },
  { question: '[שם], איך את/ה מנהל/ת את הזמן שלך בצורה הכי יעילה?', category: 'business' },
  { question: '[שם], מה הייתה ההצלחה הכי גדולה שלך השנה?', category: 'business' },
  { question: '[שם], מה הדבר הראשון שאת/ה בודק/ת כשאת/ה מגייס/ת עובד חדש?', category: 'business' },
  { question: '[שם], מה התחביב שעוזר לך להיות טוב/ה יותר בעבודה?', category: 'business' },
  { question: '[שם], מי כאן הכי סביר שיעבוד עד 2 בלילה כל יום?', category: 'business' },
  { question: '[שם], מה הדבר הכי חשוב שלמדת על ניהול אנשים?', category: 'business' },
  { question: '[שם], מה הכישלון שהכי בנה אותך מבחינה מקצועית?', category: 'business' },
  { question: '[שם], מה את/ה הכי אוהב/ת בתחום העיסוק שלך?', category: 'business' },
  { question: '[שם], מה הדבר שהיית משנה בשוק העבודה הישראלי?', category: 'business' },
  { question: '[שם], איך את/ה מתמודד/ת עם לקוחות קשים?', category: 'business' },
  { question: '[שם], מה הדבר הראשון שאת/ה עושה כשאת/ה מגיע/ה למשרד?', category: 'business' },
  { question: '[שם], מה הערך הכי חשוב לחברה שאת/ה עובד/ת בה?', category: 'business' },
  { question: '[שם], מי כאן הכי סביר שיפתח סטארט-אפ מצליח?', category: 'business' },
  { question: '[שם], מה הפגישה הכי מוזרה שהייתה לך בחיים?', category: 'business' },
  { question: '[שם], מה הדבר שהכי מעורר בך השראה בעולם העסקים?', category: 'business' },
  { question: '[שם], איך את/ה רואה את התחום שלך בעוד 10 שנים?', category: 'business' },
  { question: '[שם], מה העצה הכי גרועה שקיבלת אי פעם?', category: 'business' },
  { question: '[שם], מה הדבר שהכי עוזר לך להתרכז?', category: 'business' },
  { question: '[שם], מה את/ה הכי מעריך/ה אצל המתחרים שלך?', category: 'business' },
  { question: '[שם], מה היית עושה אם היית פורש/ת מחר לגמלאות?', category: 'business' },
  { question: '[שם], מה הדבר הכי חשוב שלמדת על משא ומתן?', category: 'business' },
  { question: '[שם], מי כאן הכי סביר שיסגור את העסקה הגדולה של הערב?', category: 'business' },
  { question: '[שם], מה הדבר שהכי מפחיד אותך בעולם העסקים?', category: 'business' },
  { question: '[שם], מה הפרויקט הבא שאת/ה מתכנן/ת להשיק?', category: 'business' },
  { question: '[שם], מה העבודה הכי "קטנה" שעשית בדרך למעלה?', category: 'business' },
  { question: '[שם], מה את/ה עושה כדי להישאר מעודכן/ת בתחום שלך?', category: 'business' },
  { question: '[שם], מה הדבר הכי חשוב שלמדת על איזון בין עבודה לחיים?', category: 'business' },
  { question: '[שם], מי כאן הכי סביר שיכתוב ספר על הקריירה שלו?', category: 'business' },
  { question: '[שם], מה הזיכרון הכי חזק שלך מהיום הראשון בעבודה הנוכחית?', category: 'business' },
  { question: '[שם], מה הדבר שהכי משמח אותך בסוף יום עבודה מוצלח?', category: 'business' },
  { question: '[שם], מה הטיפ שלך לנטוורקינג יעיל?', category: 'business' },
  { question: '[שם], מה הדבר הראשון שתעשה/י עם הבונוס הבא שלך?', category: 'business' },
  { question: '[שם], מה התכונה שהכי עוזרת לך להצליח?', category: 'business' },
  { question: '[שם], מי כאן הכי סביר שיהיה המנטור הבא שלך?', category: 'business' },
  { question: '[שם], מה הדבר שהכי מחבר בין כל האנשים כאן בשולחן מבחינה מקצועית?', category: 'business' },
  { question: '[שם], מה הדבר הראשון שתעשה/י מחר בבוקר במשרד?', category: 'business' },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    
    const user = await base44.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Check existing questions
    const existing = await base44.asServiceRole.entities.GameQuestion.list();
    const existingIds = new Set(existing.map(q => q.question));

    const toInsert = ADDITIONAL_QUESTIONS.filter(q => !existingIds.has(q.question));

    if (toInsert.length === 0) {
      return Response.json({ message: 'All questions already exist', count: 0 });
    }

    // Bulk insert in batches of 50
    let inserted = 0;
    for (let i = 0; i < toInsert.length; i += 50) {
      const batch = toInsert.slice(i, i + 50);
      const result = await base44.asServiceRole.entities.GameQuestion.bulkCreate(batch.map(q => ({
        question: q.question,
        category: q.category,
        game_type: 'question_game',
        is_active: true,
      })));
      inserted += result.length;
    }

    return Response.json({ 
      message: 'Questions seeded successfully', 
      inserted,
      total: ADDITIONAL_QUESTIONS.length 
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});